-- Create approved admin emails table
create table public.approved_admin_emails (
  email text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Pre-approve the default admin email
insert into public.approved_admin_emails (email)
values ('matthewconsult@gmail.com')
on conflict (email) do nothing;

-- Create admins profiles table linked to auth.users
create table public.admins (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text,
  role text default 'Super Admin' not null,
  bio text default 'Managing the Eikon Peters Immigration platform content and leads.',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create blog_posts table
create table public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  excerpt text,
  content text not null,
  category text not null,
  author text default 'Eikon Peters' not null,
  date text not null,
  image text,
  tags text[] default '{}'::text[] not null,
  video_url text,
  is_featured boolean default false not null,
  is_popular boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create guides table
create table public.guides (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  category text not null,
  image text,
  file_url text not null,
  pages integer default 0 not null,
  file_size text default '0MB' not null,
  button_text text default 'Download Free Guide' not null,
  is_featured boolean default false not null,
  is_popular boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create leads table
create table public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  guide text not null,
  status text default 'New' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on all tables
alter table public.approved_admin_emails enable row level security;
alter table public.admins enable row level security;
alter table public.blog_posts enable row level security;
alter table public.guides enable row level security;
alter table public.leads enable row level security;

-- RLS Policies

-- approved_admin_emails policies
create policy "Allow admins to view approved emails" on public.approved_admin_emails
  for select to authenticated using (exists (select 1 from public.admins where admins.id = auth.uid()));

create policy "Allow admins to manage approved emails" on public.approved_admin_emails
  for all to authenticated using (exists (select 1 from public.admins where admins.id = auth.uid()));

-- admins policies
create policy "Allow admins to view their own profile" on public.admins
  for select to authenticated using (id = auth.uid());

create policy "Allow admins to update their own profile" on public.admins
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- blog_posts policies
create policy "Allow public read access to blog posts" on public.blog_posts
  for select using (true);

create policy "Allow admins to manage blog posts" on public.blog_posts
  using (exists (select 1 from public.admins where admins.id = auth.uid()));

-- guides policies
create policy "Allow public read access to guides" on public.guides
  for select using (true);

create policy "Allow admins to manage guides" on public.guides
  using (exists (select 1 from public.admins where admins.id = auth.uid()));

-- leads policies
create policy "Allow public to insert leads" on public.leads
  for insert with check (true);

create policy "Allow admins to manage leads" on public.leads
  using (exists (select 1 from public.admins where admins.id = auth.uid()));


-- Trigger function to automatically add newly registered users to public.admins
-- if their email is in approved_admin_emails
create or replace function public.handle_new_user()
returns trigger as $$
begin
  if exists (select 1 from public.approved_admin_emails where email = new.email) then
    insert into public.admins (id, email, name)
    values (
      new.id,
      new.email,
      coalesce(new.raw_user_meta_data->>'name', 'Admin User')
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to run after a user registers in auth.users
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- SEED INITIAL DATA

-- Seed Blog Posts
insert into public.blog_posts (id, title, slug, excerpt, content, category, author, date, image, tags, video_url, is_featured, is_popular) values
(1, 'Understanding the UK Global Talent Visa (Image Top + Video Middle)', 'understanding-uk-global-talent-visa', 'Everything you need to know about the Global Talent Visa route for leaders in tech, arts, and research.', '
      <p>The Global Talent visa is a UK immigration route for people who are leaders, or potential leaders, in certain fields. These include academia or research, arts and culture, and digital technology.</p>
      <h2>Key Benefits</h2>
      <ul>
        <li>No minimum salary requirement</li>
        <li>No English language requirement for the initial application</li>
        <li>Fast track to settlement (Permanent Residency) in 3 years</li>
      </ul>
      [[VIDEO]]
      <p>Applying for this visa involves a two-stage process: endorsement and visa application...</p>
', 'Global Talent Visa', 'Eikon Peters', 'May 10, 2026', 'https://images.unsplash.com/photo-1513530534585-c7b1394c6d51?q=80&w=2071&auto=format&fit=crop', array['UK', 'Technology', 'Work'], 'https://www.youtube.com/embed/dQw4w9WgXcQ', true, true),

(2, 'Top 5 Tips for a Successful Student Visa Application (Image Only)', 'tips-successful-student-visa-application', 'Don''t let simple mistakes ruin your dreams of studying abroad. Follow these proven tips.', '
      <p>Studying in a new country is an exciting opportunity, but the visa application process can be daunting. Here are our top tips for success.</p>
      <h2>1. Financial Documentation</h2>
      <p>Ensure you have clear evidence of funds to cover your tuition and living costs...</p>
', 'Student Visa', 'Eikon Peters', 'May 8, 2026', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=2070&auto=format&fit=crop', array['Canada', 'Education', 'Study Abroad'], null, false, true),

(3, 'Navigating Post-Brexit Immigration Rules (Video Only)', 'navigating-post-brexit-immigration-rules', 'How the new points-based system affects EU and non-EU citizens looking to move to the UK.', '
      <p>The UK''s immigration landscape has changed significantly post-Brexit. The new points-based system treats EU and non-EU citizens equally...</p>
', 'Immigration Policy', 'Eikon Peters', 'May 5, 2026', 'https://images.unsplash.com/photo-1521295121812-32007ef78672?q=80&w=2070&auto=format&fit=crop', array['UK', 'Policy', 'EU', 'Brexit'], 'https://www.youtube.com/embed/zO2v-65Y1jY', false, false),

(4, 'Canada Express Entry: A Complete Guide for 2026', 'canada-express-entry-complete-guide', 'Learn how to calculate your CRS score and increase your chances of obtaining Canadian Permanent Residency.', '
      <p>Canada''s Express Entry system remains one of the fastest ways for skilled workers to immigrate to Canada. In 2026, several new categories have been introduced...</p>
', 'Express Entry', 'Sarah Johnson', 'May 12, 2026', 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=2070&auto=format&fit=crop', array['Canada', 'Permanent Residency', 'Skilled Worker'], null, true, true),

(5, 'The Rise of Digital Nomad Visas: Where to Go in 2026', 'rise-of-digital-nomad-visas-2026', 'More countries are opening their doors to remote workers. We review the best options for digital nomads this year.', '
      <p>Working from anywhere in the world is no longer a dream but a reality for millions. Countries like Spain, Portugal, and Greece have launched competitive Digital Nomad visas...</p>
', 'Digital Nomad Visa', 'Mark Evans', 'May 14, 2026', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop', array['Remote Work', 'Lifestyle', 'Europe'], null, false, false),

(6, 'Healthcare Professional Migration to Australia', 'healthcare-migration-australia', 'Australia is facing a critical shortage of healthcare workers. Find out how doctors and nurses can fast-track their visa applications.', '
      <p>The Australian government has prioritized healthcare professionals in its latest migration planning levels. Qualified doctors and nurses can benefit from priority processing...</p>
', 'Work Visa', 'Jane Smith', 'May 1, 2026', 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=2070&auto=format&fit=crop', array['Australia', 'Healthcare', 'Nursing'], null, false, true)
on conflict (id) do update set
  title = excluded.title,
  slug = excluded.slug,
  excerpt = excluded.excerpt,
  content = excluded.content,
  category = excluded.category,
  author = excluded.author,
  date = excluded.date,
  image = excluded.image,
  tags = excluded.tags,
  video_url = excluded.video_url,
  is_featured = excluded.is_featured,
  is_popular = excluded.is_popular;

-- Seed Guides
insert into public.guides (id, title, excerpt, category, image, file_url, pages, file_size, button_text, is_featured, is_popular) values
(1, 'Complete UK Immigration Guide 2026', 'A comprehensive PDF guide covering all major visa routes, requirements, and relocation tips for the United Kingdom.', 'Immigration Policy', 'https://images.unsplash.com/photo-1513530534585-c7b1394c6d51?q=80&w=2071&auto=format&fit=crop', '/assets/guides/uk-immigration-guide-2026.pdf', 15, '2.8MB', 'Download Free Guide', true, true),
(2, 'Self-Sponsorship Visa Checklist', 'Everything you need to prepare for a successful self-sponsorship visa application in the UK.', 'Work Visa', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2070&auto=format&fit=crop', '/assets/guides/self-sponsorship-checklist.pdf', 8, '1.5MB', 'Download Free Checklist', false, true),
(3, 'Global Talent Visa Roadmap', 'A step-by-step roadmap to securing endorsement and your Global Talent visa.', 'Global Talent Visa', 'https://images.unsplash.com/photo-1507679799987-c7377ec48699?q=80&w=2071&auto=format&fit=crop', '/assets/guides/global-talent-roadmap.pdf', 12, '2.1MB', 'Download Free Roadmap', true, false),
(4, 'Canada Student Visa Handbook', 'Complete guide for international students planning to study in Canada, from application to arrival.', 'Student Visa', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=2070&auto=format&fit=crop', '/assets/guides/canada-student-handbook.pdf', 24, '4.2MB', 'Download Free Handbook', false, true)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  category = excluded.category,
  image = excluded.image,
  file_url = excluded.file_url,
  pages = excluded.pages,
  file_size = excluded.file_size,
  button_text = excluded.button_text,
  is_featured = excluded.is_featured,
  is_popular = excluded.is_popular;

-- Reset sequence values to match the seeded IDs
select setval(pg_get_serial_sequence('public.blog_posts', 'id'), coalesce((select max(id) from public.blog_posts), 1));
select setval(pg_get_serial_sequence('public.guides', 'id'), coalesce((select max(id) from public.guides), 1));

-- Grant table privileges to authenticated, anon, and service_role roles
grant select, insert, update, delete on public.approved_admin_emails to authenticated, service_role;

grant select, insert, update, delete on public.admins to authenticated, service_role;

grant select on public.blog_posts to anon, authenticated, service_role;
grant insert, update, delete on public.blog_posts to authenticated, service_role;

grant select on public.guides to anon, authenticated, service_role;
grant insert, update, delete on public.guides to authenticated, service_role;

grant insert on public.leads to anon, authenticated, service_role;
grant select, update, delete on public.leads to authenticated, service_role;


